# Job Data Exporation

## Objective
Understand the struture and quality of jobs_practice_2 before building a pipeline

## Source
- jobs_practice_2.csv

## Import relevant libraries and data

In [8]:
import pandas as pd 

job_data = pd.read_csv("../data/jobs_practice_2.csv")
job_data

,job_id,order_date,customer_name,region,product_line,units_completed,revenue,material_cost,labor_cost,freight_cost,rush_flag,discount_pct,status,quoted_ship_date,actual_ship_date,rework_hours
0,2001,2/12/2026,Valley Med,Northeast,Implants,57,8213.08,2485.21,939.94,822.80,N,5.0,Shipped,2/20/2026,2/23/2026,2.1
1,2002,2/25/2026,Acme Health,Midwest,Kits,342,41522.11,21070.40,5604.65,384.16,N,0.0,Cancelled,3/5/2026,NaN,0.0
2,2003,2/24/2026,Valley Med,Midwest,Components,306,43906.96,14198.38,5039.45,591.27,N,2.5,Cancelled,3/6/2026,NaN,0.0
3,2004,3/11/2026,Metro Ortho,West,Custom Assemblies,319,0.00,18257.42,3340.47,198.70,N,2.5,Cancelled,3/20/2026,NaN,0.0
4,2005,2/14/2026,Beacon Surgical,West,Implants,80,8631.69,2758.61,972.56,842.95,N,10.0,Shipped,2/22/2026,3/3/2026,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2076,1/17/2026,Valley Med,South,Kits,41,6207.89,2993.42,742.12,616.05,N,5.0,In Production,1/27/2026,NaN,3.3
76,2077,3/1/2026,Summit Care,Northeast,Components,318,24537.92,9162.73,4011.28,475.56,N,2.5,Shipped,3/8/2026,3/14/2026,7.3
77,2078,3/1/2026,Valley Med,Northeast,Custom Assemblies,74,4133.13,1512.97,930.62,730.95,Y,7.5,Shipped,3/9/2026,3/7/2026,3.7
78,2079,2/11/2026,North Clinic,Midwest,Custom Assemblies,354,56375.05,17627.61,7585.25,896.69,Y,10.0,Shipped,2/24/2026,2/28/2026,2.7
79,2080,1/23/2026,Pioneer Labs,Midwest,Components,332,45309.05,14413.00,7349.71,280.12,N,2.5,Shipped,2/3/2026,2/8/2026,9.3

## Schema Validation (Structure Check)

Questions
- Are columns named consistently?
- Are numbers actually numeric?
- Are dates strings?

In [11]:
job_data.head(5)

,job_id,order_date,customer_name,region,product_line,units_completed,revenue,material_cost,labor_cost,freight_cost,rush_flag,discount_pct,status,quoted_ship_date,actual_ship_date,rework_hours
0,2001,2/12/2026,Valley Med,Northeast,Implants,57,8213.08,2485.21,939.94,822.80,N,5.0,Shipped,2/20/2026,2/23/2026,2.1
1,2002,2/25/2026,Acme Health,Midwest,Kits,342,41522.11,21070.40,5604.65,384.16,N,0.0,Cancelled,3/5/2026,NaN,0.0
2,2003,2/24/2026,Valley Med,Midwest,Components,306,43906.96,14198.38,5039.45,591.27,N,2.5,Cancelled,3/6/2026,NaN,0.0
3,2004,3/11/2026,Metro Ortho,West,Custom Assemblies,319,0.00,18257.42,3340.47,198.70,N,2.5,Cancelled,3/20/2026,NaN,0.0
4,2005,2/14/2026,Beacon Surgical,West,Implants,80,8631.69,2758.61,972.56,842.95,N,10.0,Shipped,2/22/2026,3/3/2026,0.0

In [12]:
job_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            80 non-null     int64
 1   order_date        80 non-null     object
 2   customer_name     80 non-null     object
 3   region            80 non-null     object
 4   product_line      80 non-null     object
 5   units_completed   80 non-null     int64
 6   revenue           80 non-null     float64
 7   material_cost     80 non-null     float64
 8   labor_cost        80 non-null     float64
 9   freight_cost      80 non-null     float64
 10  rush_flag         80 non-null     object
 11  discount_pct      80 non-null     float64
 12  status            80 non-null     object
 13  quoted_ship_date  80 non-null     object
 14  actual_ship_date  53 non-null     object
 15  rework_hours      80 non-null     float64
dtypes: float64(6), int64(2), object(8)
memory usage: 10.1+ KB

### Observations
- Columns are named consistently
- Numeric columns look like they are coming in as numerics
- Dates are coming in as text

## Null / missing data check

Questions
- Which columns are critical?
- Which columns contain Nulls?
    - Are nulls acceptable here?

In [14]:
job_data.isnull().sum()

job_id               0
order_date           0
customer_name        0
region               0
product_line         0
units_completed      0
revenue              0
material_cost        0
labor_cost           0
freight_cost         0
rush_flag            0
discount_pct         0
status               0
quoted_ship_date     0
actual_ship_date    27
rework_hours         0
dtype: int64

### Observations
- actual_ship_date has 27 null values
    - this might be ok because thouse jobs might not have shipped yet